FROM postgres:17

# Install build & test dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    postgresql-server-dev-17 \
    pgxnclient \
    perl \
    libtest-harness-perl \
    pgtap \
    && rm -rf /var/lib/apt/lists/*

# Install pgTAP
RUN pgxn install pgtap

# Copy extension source
COPY . /build/pg_accumulator
WORKDIR /build/pg_accumulator
